auth:
  JWT_ALG: HS256
  JWT_EXP: 15

database:
  DB_HOST: "127.0.0.1"
  DB_PORT: 5321
  DB_NAME: "postgres2"

admin:
  ADMIN_EMAIL: "admin@example.com" 
  ADMIN_FIRST_NAME: "admin"
  ADMIN_LAST_NAME: "admin"