auth:
  JWT_ALG: HS256
  JWT_EXP: 15
  JWT_REFRESH_EXP: 1440 # 1 day

database:
  DB_USERNAME: "postgres"
  DB_HOST: "127.0.0.1"
  DB_PORT: 5321
  DB_NAME: "postgres"
  DB_ECHO: true

mongo:
  MG_USERNAME: "mongo"
  MG_HOST: "127.0.0.1"
  MG_PORT: 27017
  MG_DBNAME: "mongo"

admin:
  ADMIN_EMAIL: "admin@example.com" 
  ADMIN_FIRST_NAME: "admin"
  ADMIN_LAST_NAME: "admin"